image: jgoldfar/latex-julia-docker:release-latest

pipelines:
  default:
    - step:
        script:
#          - apt-get update && apt-get install -y curl
          - julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.test(); exit()'
